# Generated by Django 3.2 on 2022-10-26 21:53

import django.core.files.storage
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_interface", "0027_theme_list_filter_removal_links"),
    ]

    operations = [
        migrations.AlterField(
            model_name="theme",
            name="logo",
            field=models.FileField(
                blank=True,
                help_text="Leave blank to use the default Django logo",
                storage=django.core.files.storage.FileSystemStorage(
                    base_url="/", location="./static/"
                ),
                upload_to="admin-interface/logo/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["gif", "jpg", "jpeg", "png", "svg"]
                    )
                ],
                verbose_name="logo",
            ),
        ),
    ]


#
